version: "3.7"

services:
  puppeth:
    image: xinfinorg/xdcsubnets:latest
    entrypoint: ["puppeth"]
    volumes:
      - "./puppeth:/root/.puppeth"
  subnet1:
    # image: xinfinorg/xdcsubnets:latest
    image: localbuid-subnet-dctemp:latest    
    volumes:
      - "./xdcchain1:/work/xdcchain"
      - "../../xinfin-script/setup-envs/subnet/genesis.json:/work/genesis.json"
    restart: "always"
    env_file: 
      - "../../xinfin-script/setup-envs/subnet/common.env"
      - "../../xinfin-script/setup-envs/subnet/subnet-1.env"
    network_mode: "host" 
  subnet2:
    # image: xinfinorg/xdcsubnets:latest    
    image: localbuid-subnet-dctemp:latest  
    volumes:
      - "./xdcchain2:/work/xdcchain"
      - "../../xinfin-script/setup-envs/subnet/genesis.json:/work/genesis.json"
    restart: "always"
    env_file:
      - "../../xinfin-script/setup-envs/subnet/common.env"
      - "../../xinfin-script/setup-envs/subnet/subnet-2.env"
    network_mode: "host" 
  subnet3:
    # image: xinfinorg/xdcsubnets:latest    
    image: localbuid-subnet-dctemp:latest  
    volumes:
      - "./xdcchain3:/work/xdcchain"
      - "../../xinfin-script/setup-envs/subnet/genesis.json:/work/genesis.json"
    restart: "always"
    env_file: 
      - "../../xinfin-script/setup-envs/subnet/common.env"
      - "../../xinfin-script/setup-envs/subnet/subnet-3.env"
    network_mode: "host" 
  subnet4:
    # image: xinfinorg/xdcsubnets:latest    
    image: localbuid-subnet-dctemp:latest  
    volumes:
      - "./xdcchain4:/work/xdcchain"
      - "../../xinfin-script/setup-envs/subnet/genesis.json:/work/genesis.json"
    restart: "always"
    env_file:
      - "../../xinfin-script/setup-envs/subnet/common.env"
      - "../../xinfin-script/setup-envs/subnet/subnet-4.env"
    network_mode: "host" 
  subnet5:
    # image: xinfinorg/xdcsubnets:latest    
    image: localbuid-subnet-dctemp:latest  
    volumes:
      - "./xdcchain5:/work/xdcchain"
      - "../../xinfin-script/setup-envs/subnet/genesis.json:/work/genesis.json"
    restart: "always"
    env_file: 
      - "../../xinfin-script/setup-envs/subnet/common.env"
      - "../../xinfin-script/setup-envs/subnet/subnet-5.env"
    network_mode: "host" 
  bootnode:
    image: xinfinorg/xdcsubnets:latest
    restart: "always"
    env_file: 
      - "../../xinfin-script/setup-envs/subnet/common.env"
    volumes:
      - "./bootnodes:/work/bootnodes"
    entrypoint: ["bash","/work/start-bootnode.sh"]
    command: ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
    ports:
      - "30301:30301/tcp"
      - "30301:30301/udp"

  stats:
    image: xinfinorg/subnet-stats-service:latest
    # image: 13d52f5b1acb
    # image: localbuild-stats
    restart: "always"
    env_file: 
      - "../../xinfin-script/setup-envs/subnet/common.env"
    volumes:
      - "./stats-service/logs:/app/logs"
    ports:
      - "3000:3000"
    network_mode: "host"
  relayer:
    image: xinfinorg/xdc-relayer:latest
    restart: "always"
    env_file: 
      - "../../xinfin-script/setup-envs/subnet/common.env"
  # mainnet:
  #   image: xinfinorg/devnet:latest
  #   volumes:
  #     - "./xdcchain_mainnet:/work/xdcchain"
  #   restart: "always"
  #   environment:
  #     NODE_NAME: ${PARENTCHAIN_NODE_NAME}
  #     LOG_LEVEL: ${LOG_LEVEL}
  #   ports:
  #     - "40313:30303"
  #     - "9555:8545"
  #     - "9565:8555"